# Generated by Django 5.1.1 on 2024-09-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryYields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('one_mo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('two_mo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('three_mo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('four_mo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('six_mo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('one_yr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('two_yr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('three_yr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('five_yr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('seven_yr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ten_yr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('twenty_yr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('thirty_yr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('source', models.CharField(max_length=100)),
                ('interest_rate_data_type', models.CharField(max_length=100)),
                ('time_period', models.CharField(max_length=100)),
            ],
        ),
    ]
